### ISSUE TITLE
electrolysis investment costs

### ISSUE THREAD

**Issue by lisazeyen** [PyPSA/technology-data#109]
## Investment cost assumptions of electrolysis from DEA

Investment cost assumptions of DEA are very optimistic, especially for the near-term. Cost could be adjusted to a smaller plant size (1 MW), and the upper uncertainty bound from DEA.

**Comment by fvdborre** [comment]
In a recent BCG report the cost projections of H2 is increased because of a more realistic cost estimation based on "complex 'real-life' electrolyzer systems incl. BOP,a many components with limited cost reduction potential".

![image](https://github.com/PyPSA/technology-data/assets/140972560/6a6ddca5-3bc1-4165-b5b0-614ab01681af)
https://media-publications.bcg.com/Turning-the-European-Green-H2-Dream-into-Reality.pdf

Furthermore, a Dutch study finds also much higher projected investment costs.
![image](https://github.com/PyPSA/technology-data/assets/140972560/fa3d40ba-638b-47ad-929a-24482cd2f859)
Source: https://energy.nl/wp-content/uploads/tno-2022-p10111_detzweeda_projections-of-electrolyzer-investment-cost-reduction-through-learning-curve-analysis.pdf

**Comment by p-glaum** [comment]
![image](https://github.com/PyPSA/technology-data/assets/95913147/c469f9ee-dd1a-4cd0-8d55-bf8209d03560)
from https://zenodo.org/records/10101328

**Comment by euronion** [comment]
Mind this refers to PEM electrolysis, while we are usually (and in the DEA data) assuming Alkaline

**Comment by martavp** [comment]
They also take higher cost assumptions in the [H2 network paper from DTU using Balmorel]( https://www.researchsquare.com/article/rs-3185467/v1), which is one of the reasons (not the only one!) that makes SMR-CC competitive in their results. 
![cost_Kountouris](https://github.com/PyPSA/technology-data/assets/30744159/91a84b4b-8c4d-49d6-870f-4560f8b656df)

**Comment by fvdborre** [comment]
In a Dutch rapport used to determine the height of the financial support ( SDE++) they assume an investment support of 1800€/kW.

![image](https://github.com/PyPSA/technology-data/assets/140972560/932fc4fa-8f92-41e5-8f44-e349a14daddb)
https://www.pbl.nl/sites/default/files/downloads/pbl-2021-conceptadvies-sde-plus-plus-2022-waterstofproductie-via-elektrolyse-4392.pdf

Many countries have a hydrogen strategy or a hydrogen support system. I assume the figures used in the context of support schemes should be reliable sources of information for the current costs. I believe figures provided by technology suppliers tend to underestimate the costs.

**Comment by lisazeyen** [comment]
My suggestion
- assume IEA cost assumptions today (1700 USD/kW), 2025 (850 US/kW), 2030 (680 USD/kW) (from  [IEA Global Hydrogen Review 2023](https://iea.blob.core.windows.net/assets/8d434960-a85c-4c02-ad96-77794aaa175d/GlobalHydrogenReview2023.pdf#page=74) and 2050 (mean 400 USD/kW)  from [IEA world energy outlook 2023](https://iea.blob.core.windows.net/assets/ed1e4c42-5726-4269-b801-97b3d32e117c/WorldEnergyOutlook2023.pdf)
p.305 "Net Zero Emission" Scenario
- keep DEA assumptions about lifetime, FOM


## Checked sources (including the above mentioned)

### [BCG report](https://media-publications.bcg.com/Turning-the-European-Green-H2-Dream-into-Reality.pdf)
* p.6 2030 1700 Eur/kW, efficiency 62%, lifetime 15 years

### [TNO report 2022 (Amsterdam, Netherlands)](https://energy.nl/wp-content/uploads/tno-2022-p10111_detzweeda_projections-of-electrolyzer-investment-cost-reduction-through-learning-curve-analysis.pdf)
- current cost alkaline electrolysis 1800 Eur/kW_elec (20 MW plant), 1400 Eur/kW (1 GW plant)
-  one component learnign curve: assuming learning rate of 12-20%, cost in 2030 1100-1350 Eur/kW_elec (conservative) and 600-850 Eur/kW_elec (optimistic), in 2050 cost reduction of 50-80%  (280 Eur/kW-900 Eur/kW)
-<mark style="background: #ffd400"> -> if we take mean values than today 1600 Eur/kW, 2030 975 Eur/kW, 2050 590 Eur/kW</mark> <mark style="background: #ff6666">I think 590 Eur/kW in 2050 is too high comparing to other sources e.g. IEA</mark>
- three component learning curve (p.8) results in 950-1400 Eur/kW_elec in 2030, 700-900 Eur/kW_elec in 2050

### [From the Odenweller paper input excel](https://github.com/aodenweller/green-h2-upscaling/blob/master/01_input_data/Electrolyser_Data_Complete_Efuels_JE_FU_AO.xlsx)
- much lower investment costs than what we assume
- this paper is cited also in the [DTU preprint](https://www.researchsquare.com/article/rs-3185467/v1) Marta mentioned for the electrolysis investment costs but investment cost don't fit to the source?



![electrolyser_data_odenweller](https://github.com/PyPSA/technology-data/assets/35347358/3109826d-70a3-437e-bb66-28418b090c12)
- earlier reports assumed much larger investment cost reductions 




### [Dutch report](https://www.pbl.nl/sites/default/files/downloads/pbl-2021-conceptadvies-sde-plus-plus-2022-waterstofproductie-via-elektrolyse-4392.pdf)
today 1800 Eur/kW


### [IEA Global Hydrogen Review 2023](https://iea.blob.core.windows.net/assets/8d434960-a85c-4c02-ad96-77794aaa175d/GlobalHydrogenReview2023.pdf#page=74)

- investment cost today 1700 USD/kW ~ 1560 Eur/kW for alkaline electrolysis (but in Europe due to inflation up to 40% increase, in China 350-1300 USD/kW)
- Based on capacity deployment of the announced projects, the
cost of an installed electrolyser could go down compared to 2023 by 50% by 2025 (which would result in ~780 Eur/kW)
and by 60% by 2030, reaching about USD 720-810/kW
- p.75 "While electrolyser CAPEX increased in 2023 by 15% compared to 2021, CAPEX could be reduced by 60-70% by 2030"

### [IEA world energy outlook 2023](https://iea.blob.core.windows.net/assets/ed1e4c42-5726-4269-b801-97b3d32e117c/WorldEnergyOutlook2023.pdf)
p.305


![iea_world_outlook](https://github.com/PyPSA/technology-data/assets/35347358/79aae585-70f0-4caa-96fe-c6b9b8778a0e)




### [Comparison investment cost in SI for the learning paper](![f18934de27e674b6e079b7cc3faff225.png](:/382a6ac2f4bc44048a5c8b632bd988e9))
- earlier reports (which we had in the SI) assumed much larger investment cost reductions 

![electrolysis_SI_learningpaper](https://github.com/PyPSA/technology-data/assets/35347358/9ddc9fa0-2936-4c2a-9a58-63e2214bcf1d)


### [DEA for small 1 MW plant p.128](https://ens.dk/sites/ens.dk/files/Analyser/technology_data_for_renewable_fuels.pdf)
- seems to be very low for 2030 (even the upper uncertainty) compared to other sources
![dea_1MW_electrolysis](https://github.com/PyPSA/technology-data/assets/35347358/37e4d834-e43c-42c4-8f77-1f9b529ca587)

**Comment by fvdborre** [comment]
The IEA places a significant emphasis on announced electrolyzer plant projects, yet many of these announcements were made before the necessary policies were in place to support such initiatives. Consequently, these announcements do not result from policy support but rather act as drivers for policy development. The primary objective behind unveiling large electrolyzer plant projects is not necessarily their construction but rather the influence they wield on policy direction. Consequently, it is advisable to disregard the announcements and focus solely on projects with a Final Investment Decision (FID). This approach is crucial for maintaining accuracy in IEA's cost projections.
![image](https://github.com/PyPSA/technology-data/assets/140972560/40161f82-3d37-4e7b-b0c1-3550b1b5ff71)

When extrapolating historical values for installed electrolyzer plant capacity, a limited dataset yields the following trend. While four data points may seem scant, it provides a more reliable foundation than relying on announced projects.
![image](https://github.com/PyPSA/technology-data/assets/140972560/c69de1e7-dcd4-4fbc-ac11-af1c4eef04ac)
![image](https://github.com/PyPSA/technology-data/assets/140972560/7fd0ec2b-f2ec-45c8-bda7-831d4dd4c9d9)

Assuming a long-term goal of building 1000 GW electrolyzer capacity (sufficient to meet current hydrogen demand), a [logistic curve](https://en.wikipedia.org/wiki/Logistic_function) emerges with the following parameters:
- Maximum Capacity (L): 1000 
- Growth Rate (k): 0.3352
- Inflection Point (x0): 2044.3
Utilizing the 2022 cost estimate of $1700/kW from the IEA as a reference, future costs can be projected using this logistic curve , with a 12% learning curve assumed.

![image](https://github.com/PyPSA/technology-data/assets/140972560/5561ae23-72c4-4121-8b86-c5514174a91b)

**Comment by martavp** [comment]
For completeness, the DEA is currently updating their cost assumption for electrolyzers. They have asked for feedback by Dec. 4 so the updated costs will be released soon. 

For 100 MW AEC, the new capital cost assumptions are: 1200 EUR/kW (2020), 875 EUR/kW (2025), 575 EUR/kW (2030), 300 EUR/kW (2050)

These are slightly higher than your suggestion @lisazeyen, but could have the benefit of reading data from the same database. 
>assume IEA cost assumptions today (1700 USD/kW), 2025 (850 US/kW), 2030 (680 USD/kW) (from [IEA Global Hydrogen Review 2023](https://iea.blob.core.windows.net/assets/8d434960-a85c-4c02-ad96-77794aaa175d/GlobalHydrogenReview2023.pdf#page=74) and 2050 (mean 400 USD/kW) from [IEA world energy outlook 2023](https://iea.blob.core.windows.net/assets/ed1e4c42-5726-4269-b801-97b3d32e117c/WorldEnergyOutlook2023.pdf)

I'm also fine with just sticking to your suggestion @lisazeyen

**Comment by euronion** [comment]
Great to hear DEA is updating the numbers, thanks for letting us know @martavp !
I'd favour us sticking with the DEA numbers if they become available soon.

Thanks @fvdborre for your detailed analysis! In addition to the purpose of announcements you describe, I also see them as a means to increase production capacities and trigger economies of scale (in an industry where until recently production was more artisanal than industrialised).
An S-curve approach with an assumed learning rate does help for a harmonized framework (see your comment in the other issue), does require assumptions on target capacities, growth rate, learning rate and a starting point (investment costs today) - all of which I'd not feel comfortable in assuming, so we'd need to stick with IEA numbers again anyways.

**Comment by fvdborre** [comment]
The issue at hand arises from discrepancies between the figures provided by the IEA and the communication of the Hydrogen Science Coalition, found at https://h2sciencecoalition.com/ . Given this inconsistency, it is evident that at least one of the two parties must be in error.

One notable discrepancy pertains to the Compound Annual Growth Rate (CAGR) implied by the IEA's figures. A global installed capacity of 175 GW in 2030 implies a staggering 106% CAGR, a figure significantly higher than the historical electrolyzer CAGR. This projection appears unrealistically high, especially when compared to the CAGR of renewable technologies in Flanders.

![image](https://github.com/PyPSA/technology-data/assets/140972560/19a9fd94-c5a7-4a42-81b0-5667277c12fa)
 

Upon further reflection, it occurred to me that the technology behind alkaline electrolysis is not novel; it is rooted in the chloralkali process. This process is well-established, with an annual production of 100 Mt of chlorine, 83% of which utilizes membrane technology. It is crucial to note that the purported cost reductions do not accurately reflect the advancements and experience already achieved with membrane chloralkali technology.

I apologize for my critical assessment. In my experience, hydrogen is frequently employed as a delay tactic, deflecting attention from more impactful and effective measures.

**Comment by euronion** [comment]
Critical assessments are good as long as they are productive, no need to apologize.

As for IEA or the H2 sci coalition - they are likely both wrong. Which is okay, we have to see them in their specific contexts. A worthwhile read which looks at different growth rates is this paper by Odenweller et al (2022): https://www.nature.com/articles/s41560-022-01097-4

The technologies are similar but not identical.

Anyway, we are heading offtopic. How about you have a look at the revised numbers by the DEA as soon as they are out and we halt the discussion for now?

**Comment by martavp** [comment]
New cost assumptions for electrolyzers from DEA just published

https://ens.dk/sites/ens.dk/files/Analyser/technology_data_for_renewable_fuels.pdf
https://ens.dk/sites/ens.dk/files/Analyser/data_sheets_for_renewable_fuels.xlsx

> For 100 MW AEC, the new capital cost assumptions are: 1200 EUR/kW (2020), 875 EUR/kW (2025), 550 EUR/kW (2030), 300 EUR/kW (2050)
