### ISSUE TITLE
selection of alternative solar costs

### ISSUE THREAD

**Issue by martavp** [PyPSA/technology-data#2]
https://github.com/lisazeyen/technology_data/blob/4eed4ea01938d1118d27d2dd0732082102652f64/compile_cost_assumptions.py#L18

This line indicates that cost from Vartiaine should be used but then the next line avoid doing so.
Do we need the two lines?

**Comment by lisazeyen** [comment]
if solar utility or rooftop data should be taken from another source can now be chosen in the config.yaml
