### ISSUE TITLE
LNG regasification investment cost seems low

### ISSUE THREAD

**Issue by ebbekyhl** [PyPSA/technology-data#54]
Investment cost for LNG regasification ("CH4 evaporation") is given at 0.28 EUR/kW_CH4 with the explanation "Calculated, based on Fasihi et al 2017, table 1, https://www.mdpi.com/2071-1050/9/2/306". 

Tracing the source leads to the paper https://doi.org/10.1016/j.enpol.2008.12.012), which calculates to approximately 20 euro/kW, assuming 2000 load hours/year. Prior constructions (https://www.gem.wiki/Gate_LNG_Terminal) suggest the same order of magnitude. 

Anyone who is aware of more recent numbers? @martavp @fneum

**Comment by ebbekyhl** [comment]
w. 8000 load hours/year instead (might be more realistic), the capacity investment cost is in the range 71-77 EUR/kW, based on  https://doi.org/10.1016/j.enpol.2008.12.012 (100 mil USD/(bcm/a)) and  https://doi.org/10.1016/j.enpol.2008.12.012 (1.1 b USD/(12bcm/a))

**Comment by euronion** [comment]
Thanks for noticing this.

I'm not aware of more recent numbers; any numbers you might find are welcome! (like the GEM reference).

Regarding the current numbers:

These indeed seem low. There must have been a mistake when converting kEUR/mcm/a to EUR/kW, can you confirm the calculation below, which gives a value in the orders of magnitude you are suggesting.

```
74 kEUR/mcm/a
= 74 000 EUR / 1000 m^3 / a
<=> 74 000 EUR / 422.6 t / a
<=> 74 000 EUR / 5869.40 MWh / a
<=> 12.60 EUR / MWh / a
<=> 110 444 EUR / MW
<=> 110.440 EUR / kW (input)
<=> 120.05 EUR / kW (output)
```

(Neglecting CFs and only considering the Fasihi et al 2017 number; additionally:
```
1 mcm = 1000 m^3
density methane: 0.4226 t / m^3
specific energy methane: 13.8889 MWh / t
```

**Comment by euronion** [comment]
Maybe an up-to-date public figure: The German LNG terminals which are supposed to be build. The larger one at 10 bcm / a is estimated at around 1 GEUR, i.e. something like 150 EUR / kW.

**Comment by ebbekyhl** [comment]
@euronion 

Maybe I am missing some details here, but with a more simple approach I obtain half of it:

`1 mcm Natural Gas = 10.6 GWh` (https://energyeducation.ca/encyclopedia/Bcm) 

`74 k EUR / (mcm/a)`
`= 74*10^3 EUR / (10.6 GWh/a)`
`= 74*10^3 EUR / (10.6 GWh/8760h)`
`= 74*10^3 EUR / 1.2 MW`
`= 74 EUR / 1.2 kW`
`= 61.7 EUR / kW`

I based my initial numbers on $100 million per one billion cubic meter from https://doi.org/10.1016/j.enpol.2008.12.012, and not 74kEUR/mcm/a., why I now obtain a lower capacity cost. 

I guess your input-output ratio resembles some efficiency loss?

**Comment by euronion** [comment]
Ok, so first things first:

Units are a big mess in the gas industry:
* Some people like to write mcm, others Mcm and then there is MCM. Are they interchangeably? Yes/No/Maybe/Hopefully.
* 1 MCM = 1 Million m³ according to [1]
* 1 MCM = 1 Thousand m³ according to [2]
* Some use "M" as SI prefix, some as Roman number prefix, i.e. "M" = 1000, "MM" = 1000*1000, see e.g. here [3]

[1] https://www.gazprom-energy.co.uk/help-and-support/other-useful-information/energy-glossary/m/
[2] https://www.investopedia.com/terms/m/mcf.asp
[3] https://www.wallstreetmojo.com/mm-million/

You're were calculating the energy content from Natural Gas (gaseous), i.e. 

`1 bcm = 10.739 TWh` (EIA: https://www.eia.gov/energyexplained/units-and-calculators/energy-conversion-calculators.php)

In the calculation above I took the energy content of 1 000 m³ of pure, liquid methane ("CH4 evaporation", not "LNG evaporation") `= 5.869 GWh`. You take the energy content of 1 000 000 m³ of gaseous natural gas `= 10.6 GWh`. That explains the different results.

I didn't not trace back the original source, you are probably right with your calculation. I don't have access to the original publication and supplementary materials, can you share them privately with me?

**Comment by ebbekyhl** [comment]
That is indeed misleading with that many different notations. But thanks for clearing this out!

Sure. I will share it with you privately.

**Comment by euronion** [comment]
ok. From the original article it becomes clear that we are talking about bcm in gaseous form, i.e. 1 billion cubic meters of gaseous natural gas.

Documenting additionally some key aspects from the original Lochner et al (2009) publication:

> For liquefaction terminals and regasification plants, investment costs are assumed to be $265 million and **$100 million (in 2005 terms) per one billion cubic meter** annual liquefaction and **regasification capacity** respectively.
> [...]
> general notion that **LNG receiving facilities are relatively cheaper and cost only between one third and two fifths of the average liquefaction terminals.**

and

> These assumptions fit into the range of estimated costs of current and past projects, but are generally at the lower end of the range as we do not expect the currently high costs (due to high demand) to be a long-term equilibrium (see Tusiani and Shearer (2007, p. 298), Jensen (2004, p. 6), Roe (2001, p. 91)).

followed by

> Operating costs for both stages of the LNG value chain are set at 3.5 percent;
> gas consumption of liquefaction terminals is assumed to equal 5 percent of the liquefied volume (see Seeliger, 2006).
> Shipping costs  [...] we assume an average investment cost of U.S.-$1.48 million per 1000 cubic meters of LNG capacity in 2005 terms.

So let's stick with the 100 MUSD-2005 / bcm / a.

Correcting for inflation:
* HCIP factor from eurostat (2005/2015): 0.8275/1
* Conversion rate USD/EUR: 1.15 USD/1 EUR
* Cost degression (speculated in article): 0.5%/a

```
base cost * currency conversion * inflation correction * learning cost degression
= 100 MUSD-2005 / bcm / a / (1.15 USD/EUR) / (0.8275 EUR-2005/EUR-2015) * 0.995**10
= 99.95 MEUR-2015 / bcm / a
```

which is a funny coincidence. So 100 MEUR-2015/bcm/a match the 1 GEUR/10bcm/a of the German planned LNG terminals.


Concluding, going back to the calculation:

* We need to calculate with `1 bcm = 10.6 TWh`
* `CAPEX = 100 MEUR-2015/(bcm/a) = 100 MEUR-2015/(10.6 TWh/8760h) =  1e8 EUR-2015/(1.06e10 kWh/8760h) = 1 EUR-2015/(106 kW/8760) = 82.64 EUR-2015/kW`

Question is: Why is this number ~4x higher than your number that you initially stated (`~20 EUR/kW`)? ;-)

**Comment by ebbekyhl** [comment]
@euronion, great work reviewing this!

You can simply ignore my initial statement as it assumed the LNG regasification terminal to only operate 2000 h/a. Assuming it to run 8760h/a (i.e., **multiply ~20 EUR/kW by 4.38**), we end at a similar cost :-)

**Comment by euronion** [comment]
But at 2000 h / the costs should be 4.38 times higher, shouldn't they? ;-)

**Comment by ebbekyhl** [comment]
I wouldn't say so. Assuming a shorter operation period entails a higher capacity - and for the same amount of investment, the (specific) capacity cost reduces.

`100 MEUR-2015/(10.6 TWh/8760h) = 8760h*100 MEUR-2015/10.6 TWh = 82.64 EUR/kW`

`100 MEUR-2015/(10.6 TWh/2000h) = 2000h*100 MEUR-2015/10.6 TWh =18.87 EUR/kW `

**Comment by euronion** [comment]
Again we are thinking differently about the numbers:

2000 FLH/a for me are: 1 bcm max. capacity (at 8760 FLH) -> 0.228 bcm capacity per year for the same facility with the same investment cost, so 4....-ish higher.

Anyway, that number is luckily not relevant to us in this context.

Do you want to create a PR to fix this issue or should I?

**Comment by ebbekyhl** [comment]
That's fair. 

I'll let you create it. Thanks.
