### ISSUE TITLE
convert everything to 2020-Euro

### ISSUE THREAD

**Issue by lisazeyen** [PyPSA/technology-data#78]

**Comment by Irieo** [comment]
This would be a quick change requiring all dependent projects to remove the cost adjustment. We need to clearly communicate it so that users are aware of it.

**Comment by euronion** [comment]
How would you go about inflation adjustments? Assume constant 2%? Or use [HCIP](https://ec.europa.eu/eurostat/databrowser/view/tec00118/default/table?lang=en) for EU area?
