### ISSUE TITLE
Wrong currency year assumed for electrolysis

### ISSUE THREAD

**Issue by euronion** [PyPSA/technology-data#90]
DEA data states 2020 in Excel file, `compile_cost_assumption` does not adjust, assumes 2015.

**Comment by lisazeyen** [comment]
Yes, the DEA has updated some technologies and these are in 2020 Euro. One would have to go through all technologies and check for which Euro year the cost assumptions are given. Most technologies are still in 2015 Euro

**Comment by euronion** [comment]
Unfortunately other than e.g. with `offshore wind` or `solar-utility`, we don't account for this for `electrolysis` which is already in 2020 currency in the data source we use, but we assume it's 2015.
